// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG8EOhDTZdPpnOGJYDbMu2Q2T0061EXC8',
    appId: '1:973526687262:web:7e1cd612e964b7bb8cd80f',
    messagingSenderId: '973526687262',
    projectId: 'apk07-baa9b',
    authDomain: 'apk07-baa9b.firebaseapp.com',
    storageBucket: 'apk07-baa9b.appspot.com',
    measurementId: 'G-45GR3HEJ5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz4A1-fivOJ_VlRfvowePeNUp4t6NrH7M',
    appId: '1:973526687262:android:593bef76de1fcd3d8cd80f',
    messagingSenderId: '973526687262',
    projectId: 'apk07-baa9b',
    storageBucket: 'apk07-baa9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM5b-vsIl3pIGg3NRXQSqC09TbyaIG2CQ',
    appId: '1:973526687262:ios:6e8ab9ac1b0a02988cd80f',
    messagingSenderId: '973526687262',
    projectId: 'apk07-baa9b',
    storageBucket: 'apk07-baa9b.appspot.com',
    iosClientId: '973526687262-h91ptoqm0gt0crrmp8lleuf6uuebf71p.apps.googleusercontent.com',
    iosBundleId: 'com.example.pertamaLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM5b-vsIl3pIGg3NRXQSqC09TbyaIG2CQ',
    appId: '1:973526687262:ios:6e8ab9ac1b0a02988cd80f',
    messagingSenderId: '973526687262',
    projectId: 'apk07-baa9b',
    storageBucket: 'apk07-baa9b.appspot.com',
    iosClientId: '973526687262-h91ptoqm0gt0crrmp8lleuf6uuebf71p.apps.googleusercontent.com',
    iosBundleId: 'com.example.pertamaLogin',
  );
}
